#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# =============================================================================
#  This module is part of the Master's Thesis (MSc Dissertation):
#  - Fast Simulation of Neutrino Oscillations in Matter
#
#  Author:
#      Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>
#
#  Supervisors:
#      Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>
#      Michele Lucente <michele.lucente@unibo.it>
#
#  Date:
#      June 2026
# =============================================================================

"""Evolution operators for perturbative matter-density segments.

The module groups the complete evolution hierarchy. ``evolutor_zero_order``
computes the exact constant-density contribution from the spectral
decomposition of a Hamiltonian. ``evolutor_first_order`` uses those spectral
data to calculate the correction generated by a density-profile model.
``evolutor_perturbative_from_H`` combines both contributions and applies the
zero-length convention.

Functions
---------
evolutor_zero_order(...)
    Compute the exact average-density operator U0. It can also return the
    spectral data reused by the first-order calculation.
evolutor_first_order(...)
    Compute U1 from spectral projectors and a profile-model residual integral.
evolutor_perturbative_from_H(...)
    Build the perturbative segment operator U = U0 + U1 from the Hamiltonian.
evolutor_perturbative_segment(...)
    Build a reduced Hamiltonian for one profile model and evolve it perturbatively.
"""

from __future__ import annotations

from typing import Union

import torch

from tpeanuts.core.perturbative.spectral import hamiltonian_spectral_data
from tpeanuts.core.common.oscillation import OscillationParameters
from tpeanuts.core.common.potential import matter_potential
from tpeanuts.core.common.hamiltonian import (
    hamiltonian_kinetic_reduced,
    hamiltonian_matter_reduced,
)
from tpeanuts.util.constant import R_E
from tpeanuts.util.torch_util import enforce_identity_for_zero_length, infer_device_dtype
from tpeanuts.util.type import TensorLike, as_tensor, cdtype_from_real


def evolutor_zero_order(
    H: torch.Tensor,
    L: torch.Tensor,
    *,
    trace_H: torch.Tensor | None = None,
    zero_mask: torch.Tensor | None = None,
    return_spectral: bool = False,
) -> torch.Tensor | tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """Compute the exact zeroth-order operator for the average Hamiltonian.

    The function diagonalizes the traceless Hamiltonian and evaluates
    ``U0 = sum_a exp[-i(lambda_a + Tr(H)/3)L] M_a``. When requested, the same
    spectral data are returned so the first-order term can reuse them without
    a second diagonalization.

    Args:
        H: Dimensionless average Hamiltonian shaped (..., 3, 3).
        L: Dimensionless segment length.
        trace_H: Optional precomputed trace of H.
        zero_mask: Optional mask selecting segments that must return identity.
        return_spectral: Return ``(U0, spectral_data)`` when True.

    Returns:
        U0 shaped (..., 3, 3), optionally paired with its spectral data.
    """
    spectral = hamiltonian_spectral_data(H, trace_H=trace_H)
    lam = spectral["lam"]
    trace = spectral["trace"].to(dtype=lam.dtype)
    length = L.to(dtype=lam.dtype)

    phase = torch.exp(
        -1j * (lam + trace[..., None] / 3.0) * length[..., None]
    )
    U0 = (phase[..., :, None, None] * spectral["M"]).sum(dim=-3)

    if zero_mask is not None:
        U0 = enforce_identity_for_zero_length(U0, L, zero_mask)

    if return_spectral:
        return U0, spectral
    return U0


def evolutor_first_order(
    M: torch.Tensor,
    lam: torch.Tensor,
    trace_H: torch.Tensor,
    profile_model: object,
    *,
    antinu: Union[bool, torch.Tensor] = False,
    evolution_scale_m: TensorLike = R_E,
    legacy_precision: bool = False,
) -> torch.Tensor:
    """Compute the first-order correction for a density-profile model.

    Args:
        M: Spectral projectors shaped (..., 3, 3, 3).
        lam: Traceless-Hamiltonian eigenvalues shaped (..., 3).
        trace_H: Trace of the full dimensionless Hamiltonian.
        profile_model: Object exposing ``residual_integral(la, lb)``. The
            returned integral must have units of electron density times
            evolution coordinate and be broadcastable with the spectral matrix
            pairs.
        antinu: Select the antineutrino matter-potential sign.
        evolution_scale_m: Length scale used to normalize the potential.
        legacy_precision: If True, use the legacy peanuts matter-potential
            prefactor for the first-order correction.

    Returns:
        First-order correction U1 shaped (..., 3, 3).
    """
    eigenvalues_H = lam + trace_H[..., None] / 3.0
    integral = profile_model.residual_integral(
        la=eigenvalues_H[..., :, None],
        lb=eigenvalues_H[..., None, :],
    )
    potential_correction = matter_potential(
        integral,
        antinu=antinu,
        evolution_scale_m=evolution_scale_m,
        legacy_precision=legacy_precision,
    ).to(dtype=M.dtype)

    return (-1j) * torch.einsum(
        "...ab,...ai,...bj->...ij",
        potential_correction,
        M[..., :, :, 0],
        M[..., :, 0, :],
    )


def evolutor_perturbative_from_H(
    H: torch.Tensor,
    L: torch.Tensor,
    profile_model: object,
    *,
    trace_H: torch.Tensor | None = None,
    zero_mask: torch.Tensor | None = None,
    antinu: Union[bool, torch.Tensor] = False,
    evolution_scale_m: TensorLike = R_E,
    legacy_precision: bool = False,
) -> torch.Tensor:
    """Combine zeroth- and first-order evolution for one density segment.

    Args:
        H: Dimensionless average Hamiltonian shaped (..., 3, 3).
        L: Segment length in evolution coordinates.
        profile_model: Density-profile model providing the residual integral
            and perturbation mask for the first-order correction.
        trace_H: Optional precomputed trace of H.
        zero_mask: Optional mask selecting zero-length segments.
        antinu: Select the antineutrino matter-potential sign.
        evolution_scale_m: Length scale used to normalize H and the correction.
        legacy_precision: If True, use the legacy peanuts matter-potential
            prefactor for the first-order correction.

    Returns:
        Perturbative segment operator U0 + U1 shaped (..., 3, 3).
    """
    U0, spectral = evolutor_zero_order(
        H,
        L,
        trace_H=trace_H,
        return_spectral=True,
    )

    perturbation_mask = profile_model.has_perturbation().to(device=U0.device)

    # A segment with no perturbation (e.g. a constant-density segment) has a
    # zero first-order correction everywhere, and would just be masked back
    # to zero below. Skipping evolutor_first_order in that case avoids the
    # residual_integral spectral-oscillatory-integral computation entirely
    # when its result is guaranteed to be discarded.
    if not bool(torch.any(perturbation_mask)):
        U = U0
    else:
        U1 = evolutor_first_order(
            M=spectral["M"],
            lam=spectral["lam"],
            trace_H=spectral["trace"],
            profile_model=profile_model,
            antinu=antinu,
            evolution_scale_m=evolution_scale_m,
            legacy_precision=legacy_precision,
        )

        mask = perturbation_mask
        while mask.ndim < U1.ndim - 2:
            mask = mask.unsqueeze(-1)

        U = U0 + torch.where(
            mask[..., None, None],
            U1,
            torch.zeros_like(U1),
        )
    if zero_mask is not None:
        U = enforce_identity_for_zero_length(U, L, zero_mask)
    return U


@torch.no_grad()
def evolutor_perturbative_segment(
    oscillation: OscillationParameters,
    E_MeV: TensorLike,
    profile_model: object,
    *,
    debug: bool = False,
    evolution_scale_m: TensorLike = R_E,
    legacy_precision: bool = False,
) -> torch.Tensor:
    """Build a reduced Hamiltonian for one profile model and evolve it perturbatively.

    3-flavour SM only (via ``hamiltonian_kinetic_reduced``/
    ``hamiltonian_matter_reduced``); ``oscillation.DeltamSq41`` is unused.

    Args:
        oscillation: Built pmns object plus mass splittings and antinu
            selection. ``oscillation.pmns`` must expose the reduced mixing
            matrix.
        E_MeV: Neutrino energy in MeV.
        profile_model: Perturbative density-profile model exposing
            ``average``, ``length``, ``zero_mask``, ``potential``,
            ``residual_integral(la, lb)``, and ``has_perturbation()``.
        debug: If True, print diagnostic intermediate checks.
        evolution_scale_m: Positive scale in metres defining H and the
            evolution coordinate.
        legacy_precision: If True, use the legacy peanuts matter-potential
            prefactor in perturbative corrections. The segment average
            potential is supplied by the profile model.

    Returns:
        Complex segment evolutor shaped (..., 3, 3).
    """
    pmns = oscillation.pmns
    antinu = oscillation.antinu

    device, rdtype = infer_device_dtype(
        E_MeV,
        profile_model.length,
        profile_model.average,
        profile_model.potential,
    )
    cdtype = cdtype_from_real(rdtype)

    E_MeV = as_tensor(E_MeV, device=device, dtype=rdtype)
    V = profile_model.potential.to(device=device, dtype=rdtype)
    naverage = profile_model.average.to(device=device, dtype=rdtype)
    L = profile_model.length.to(device=device, dtype=rdtype)
    zero_mask = profile_model.zero_mask.to(device=device)

    Ured = pmns.reduced(antinu=antinu)
    Hkin, ki = hamiltonian_kinetic_reduced(
        DeltamSq21=oscillation.DeltamSq21,
        DeltamSq3l=oscillation.DeltamSq3l,
        E_MeV=E_MeV,
        Ured=Ured,
        evolution_scale_m=evolution_scale_m,
        return_ki=True,
        legacy_precision=legacy_precision,
    )

    H = Hkin + hamiltonian_matter_reduced(V, legacy_precision=legacy_precision)
    trace_H = (
        ki[..., 0]
        + ki[..., 1]
        + ki[..., 2]
        + V
    ).to(dtype=cdtype)

    if debug:
        herm_err = (
            H
            - H.conj().transpose(-1, -2)
        ).abs().max()

        print(
            f"[DEBUG] H Hermitian error: max|H-H†| = {herm_err.item():.4e}"
        )

        if not torch.isfinite(naverage).all():
            print("[DEBUG] naverage contains NaN or Inf.")

        if not torch.isfinite(V).all():
            print("[DEBUG] V contains NaN or Inf.")

        if not torch.isfinite(H).all():
            print("[DEBUG] H contains NaN or Inf.")

        if not torch.isfinite(L).all():
            print("[DEBUG] L contains NaN or Inf.")

    return evolutor_perturbative_from_H(
        H=H,
        L=L,
        profile_model=profile_model,
        trace_H=trace_H,
        zero_mask=zero_mask,
        antinu=antinu,
        evolution_scale_m=evolution_scale_m,
        legacy_precision=legacy_precision,
    )
