# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test5 io

Notebook equivalent of `tests/6_mceq/test5_io.py`. The original Python test module remains the source of truth; this notebook imports it and runs each numerical test and diagnostic plot in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated `mceq` test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "mceq" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original `mceq` test module, and reloads it so source changes are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree, missing optional dependencies, or unavailable external model data.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test5_io"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "6_mceq" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\6_mceq\test5_io.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes `mceq` test figures and generated artifacts under `OUTPUT_TEST_ROOT / "mceq" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots follow the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "mceq" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\mceq\test5_io


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Plot: `make_temp_output_config()`

**What is checked:** Make temp output config behavior and numerical consistency.

**Expected result:** The expected result is that the diagnostic plot call completes and writes its figure output to `OUTPUT_DIR`.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `make_temp_output_config()`

This block generates or validates files in `OUTPUT_DIR`:

- `phi_E_theta_h_from_mceq_profiles.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [4]:
run_notebook_call('make_temp_output_config()', lambda: TEST_MODULE.make_temp_output_config())


Running make_temp_output_config() ...
PASSED: make_temp_output_config()


(OutputConfig(output_dir=WindowsPath('V:/output/test/mceq/test5_io'), filename='phi_E_theta_h_from_mceq_profiles.pt', dtype=torch.float64, compressed=True, overwrite=True, save_intermediate=True),
 WindowsPath('V:/output/test/mceq/test5_io'))

## Test: `test_safe_filename_name`

**What is checked:** Safe filename name behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [5]:
run_notebook_test(TEST_MODULE.test_safe_filename_name)


Running test_safe_filename_name ...
original: nu/mu+ test:case
safe    : nu_muplus_test_case
------------------------------------------------------------------------------------------
PASSED: test_safe_filename_name


## Test: `test_angle_to_filename`

**What is checked:** Theta to filename behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [6]:
run_notebook_test(TEST_MODULE.test_angle_to_filename)


Running test_angle_to_filename ...
theta: 30.125
safe : 30p125
------------------------------------------------------------------------------------------
PASSED: test_angle_to_filename


## Test: `test_ensure_torch_extension_from_empty_extension`

**What is checked:** Ensure torch extension from empty extension behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_ensure_torch_extension_from_empty_extension`

This block generates or validates files in `OUTPUT_DIR`:

- `flux_output.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [7]:
run_notebook_test(TEST_MODULE.test_ensure_torch_extension_from_empty_extension)


Running test_ensure_torch_extension_from_empty_extension ...
filename: flux_output.pt
------------------------------------------------------------------------------------------
PASSED: test_ensure_torch_extension_from_empty_extension


## Test: `test_ensure_torch_extension_keeps_pt`

**What is checked:** Ensure torch extension keeps pt behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_ensure_torch_extension_keeps_pt`

This block generates or validates files in `OUTPUT_DIR`:

- `flux_output.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [8]:
run_notebook_test(TEST_MODULE.test_ensure_torch_extension_keeps_pt)


Running test_ensure_torch_extension_keeps_pt ...
filename: flux_output.pt
------------------------------------------------------------------------------------------
PASSED: test_ensure_torch_extension_keeps_pt


## Test: `test_ensure_torch_extension_replaces_npz`

**What is checked:** Ensure torch extension replaces npz behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_ensure_torch_extension_replaces_npz`

This block generates or validates files in `OUTPUT_DIR`:

- `flux_output.npz`
- `flux_output.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [9]:
run_notebook_test(TEST_MODULE.test_ensure_torch_extension_replaces_npz)


Running test_ensure_torch_extension_replaces_npz ...
filename: flux_output.pt
------------------------------------------------------------------------------------------
PASSED: test_ensure_torch_extension_replaces_npz


## Test: `test_build_angle_output_path_with_theta`

**What is checked:** Build theta output filename behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_build_angle_output_path_with_theta`

This block generates or validates files in `OUTPUT_DIR`:

- `flux_output.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [10]:
run_notebook_test(TEST_MODULE.test_build_angle_output_path_with_theta)


Running test_build_angle_output_path_with_theta ...
path: V:\output\test\mceq\test5_io\flux_output_numu_theta_45p000deg.pt
filename: flux_output_numu_theta_45p000deg.pt
------------------------------------------------------------------------------------------
PASSED: test_build_angle_output_path_with_theta


## Test: `test_build_angle_output_path_with_alpha_theta`

**What is checked:** Build alpha theta output filename behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_build_angle_output_path_with_alpha_theta`

This block generates or validates files in `OUTPUT_DIR`:

- `flux_output.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [11]:
run_notebook_test(TEST_MODULE.test_build_angle_output_path_with_alpha_theta)


Running test_build_angle_output_path_with_alpha_theta ...
path: V:\output\test\mceq\test5_io\flux_nue_total_nue_alpha_41p250deg_theta_43p500deg.pt
filename: flux_nue_total_nue_alpha_41p250deg_theta_43p500deg.pt
------------------------------------------------------------------------------------------
PASSED: test_build_angle_output_path_with_alpha_theta


## Test: `test_build_angle_output_path_with_alpha_theta`

**What is checked:** Build alpha theta output path behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_build_angle_output_path_with_alpha_theta`

This block generates or validates files in `OUTPUT_DIR`:

- `flux.npz`
- `flux_nue_total_nue_alpha_41p250deg_theta_43p500deg.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [12]:
run_notebook_test(TEST_MODULE.test_build_angle_output_path_with_alpha_theta)


Running test_build_angle_output_path_with_alpha_theta ...
path: V:\output\test\mceq\test5_io\flux_nue_total_nue_alpha_41p250deg_theta_43p500deg.pt
filename: flux_nue_total_nue_alpha_41p250deg_theta_43p500deg.pt
------------------------------------------------------------------------------------------
PASSED: test_build_angle_output_path_with_alpha_theta


## Test: `test_build_output_path`

**What is checked:** Build output path behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_build_output_path`

This block generates or validates files in `OUTPUT_DIR`:

- `file.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [13]:
run_notebook_test(TEST_MODULE.test_build_output_path)


Running test_build_output_path ...
path: V:\output\test\mceq\test5_io\file.pt
------------------------------------------------------------------------------------------
PASSED: test_build_output_path


## Test: `test_build_result_metadata`

**What is checked:** Build result metadata behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; 30.0.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [14]:
run_notebook_test(TEST_MODULE.test_build_result_metadata)


Running test_build_result_metadata ...
metadata keys: dict_keys(['description', 'relation', 'normalization', 'particle', 'flavour_name', 'alpha_deg', 'theta_deg', 'angle_units', 'angle_convention', 'tensor_shapes', 'format', 'extension'])
tensor shapes: {'theta_deg': (), 'E_grid_GeV': (5,), 'X_grid_gcm2': (10,), 'h_grid_km': (20,), 'flux_XE': (10, 5), 'flux_smooth_XE': (10, 5), 'dPhi_dX_XE': (10, 5), 'X_of_h_gcm2': (20,), 'dXdh_gcm2_per_km': (20,), 'source_Eh': (5, 20), 'f_Eh': (5, 20), 'phi_E_obs': (5,), 'phi_Eh': (5, 20)}
------------------------------------------------------------------------------------------
PASSED: test_build_result_metadata


## Test: `test_build_result_metadata_with_alpha_theta`

**What is checked:** Build result metadata with alpha theta behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; 41.25; 43.5.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [15]:
run_notebook_test(TEST_MODULE.test_build_result_metadata_with_alpha_theta)


Running test_build_result_metadata_with_alpha_theta ...
metadata: {'description': 'Atmospheric height-differential flux dataset.', 'relation': 'Phi(E,h) = Phi(E;X_obs) * f(h|E,theta)', 'normalization': 'Integral_h f(h|E,theta) dh = 1', 'particle': 'total_nue', 'flavour_name': 'nue', 'alpha_deg': 41.25, 'theta_deg': 43.5, 'angle_units': 'deg', 'angle_convention': {'alpha_deg': 'detector angle, when provided by the caller', 'theta_deg': 'surface-intersection atmospheric angle'}, 'tensor_shapes': {'theta_deg': (), 'E_grid_GeV': (5,), 'X_grid_gcm2': (10,), 'h_grid_km': (20,), 'flux_XE': (10, 5), 'flux_smooth_XE': (10, 5), 'dPhi_dX_XE': (10, 5), 'X_of_h_gcm2': (20,), 'dXdh_gcm2_per_km': (20,), 'source_Eh': (5, 20), 'f_Eh': (5, 20), 'phi_E_obs': (5,), 'phi_Eh': (5, 20), 'alpha_deg': ()}, 'format': 'torch', 'extension': '.pt'}
------------------------------------------------------------------------------------------
PASSED: test_build_result_metadata_with_alpha_theta


## Test: `test_cast_tensor_tree_dtype_and_device`

**What is checked:** Cast tensor tree dtype and device behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [16]:
run_notebook_test(TEST_MODULE.test_cast_tensor_tree_dtype_and_device)


Running test_cast_tensor_tree_dtype_and_device ...
dtype a: torch.float32
dtype b.c: torch.float32
dtype e[0]: torch.float32
------------------------------------------------------------------------------------------
PASSED: test_cast_tensor_tree_dtype_and_device


## Test: `test_save_phi_Eh_theta_result_creates_pt_file`

**What is checked:** Save phi eh theta result creates pt file behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [17]:
run_notebook_test(TEST_MODULE.test_save_phi_Eh_theta_result_creates_pt_file)


Running test_save_phi_Eh_theta_result_creates_pt_file ...
saved path: V:\output\test\mceq\test5_io\phi_E_theta_h_from_mceq_profiles_numu_theta_30p000deg.pt
------------------------------------------------------------------------------------------
PASSED: test_save_phi_Eh_theta_result_creates_pt_file


## Test: `test_save_with_npz_filename_still_creates_pt_file`

**What is checked:** Save with npz filename still creates pt file behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_save_with_npz_filename_still_creates_pt_file`

This block generates or validates files in `OUTPUT_DIR`:

- `phi_E_theta_h_from_mceq_profiles.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [18]:
run_notebook_test(TEST_MODULE.test_save_with_npz_filename_still_creates_pt_file)


Running test_save_with_npz_filename_still_creates_pt_file ...
saved path: V:\output\test\mceq\test5_io\phi_E_theta_h_from_mceq_profiles_numu_theta_30p000deg.pt
------------------------------------------------------------------------------------------
PASSED: test_save_with_npz_filename_still_creates_pt_file


## Test: `test_save_requires_theta_deg_key`

**What is checked:** Save requires theta deg key behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_raises.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [19]:
run_notebook_test(TEST_MODULE.test_save_requires_theta_deg_key)


Running test_save_requires_theta_deg_key ...
------------------------------------------------------------------------------------------
PASSED: test_save_requires_theta_deg_key


## Test: `test_load_phi_Eh_theta_result`

**What is checked:** Load phi eh theta result behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [20]:
run_notebook_test(TEST_MODULE.test_load_phi_Eh_theta_result)


Running test_load_phi_Eh_theta_result ...
loaded keys: dict_keys(['theta_deg', 'particle', 'flavour_name', 'E_grid_GeV', 'X_grid_gcm2', 'h_grid_km', 'flux_XE', 'flux_smooth_XE', 'dPhi_dX_XE', 'X_of_h_gcm2', 'dXdh_gcm2_per_km', 'source_Eh', 'f_Eh', 'phi_E_obs', 'phi_Eh', 'build_time_sec', 'metadata', 'metadata_json'])
------------------------------------------------------------------------------------------
PASSED: test_load_phi_Eh_theta_result


## Test: `test_save_phi_Eh_theta_with_alpha_and_load_theta_result`

**What is checked:** Save and load phi eh alpha theta result behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; 41.25; 43.5.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_save_phi_Eh_theta_with_alpha_and_load_theta_result`

This block generates or validates files in `OUTPUT_DIR`:

- `flux.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [21]:
run_notebook_test(TEST_MODULE.test_save_phi_Eh_theta_with_alpha_and_load_theta_result)


Running test_save_phi_Eh_theta_with_alpha_and_load_theta_result ...
saved path: V:\output\test\mceq\test5_io\flux_nue_total_nue_alpha_41p250deg_theta_43p500deg.pt
loaded metadata: {'description': 'Atmospheric height-differential flux dataset.', 'relation': 'Phi(E,h) = Phi(E;X_obs) * f(h|E,theta)', 'normalization': 'Integral_h f(h|E,theta) dh = 1', 'particle': 'total_nue', 'flavour_name': 'nue', 'alpha_deg': 41.25, 'theta_deg': 43.5, 'angle_units': 'deg', 'angle_convention': {'alpha_deg': 'detector angle, when provided by the caller', 'theta_deg': 'surface-intersection atmospheric angle'}, 'tensor_shapes': {'theta_deg': (), 'E_grid_GeV': (5,), 'X_grid_gcm2': (10,), 'h_grid_km': (20,), 'flux_XE': (10, 5), 'flux_smooth_XE': (10, 5), 'dPhi_dX_XE': (10, 5), 'X_of_h_gcm2': (20,), 'dXdh_gcm2_per_km': (20,), 'source_Eh': (5, 20), 'f_Eh': (5, 20), 'phi_E_obs': (5,), 'phi_Eh': (5, 20), 'alpha_deg': ()}, 'format': 'torch', 'extension': '.pt'}
------------------------------------------------------

## Test: `test_load_phi_Eh_alpha_theta_from_config`

**What is checked:** Load phi eh alpha theta from config behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: 41.25; 43.5; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_load_phi_Eh_alpha_theta_from_config`

This block generates or validates files in `OUTPUT_DIR`:

- `flux.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [22]:
run_notebook_test(TEST_MODULE.test_load_phi_Eh_alpha_theta_from_config)


Running test_load_phi_Eh_alpha_theta_from_config ...
loaded path metadata: {'description': 'Atmospheric height-differential flux dataset.', 'relation': 'Phi(E,h) = Phi(E;X_obs) * f(h|E,theta)', 'normalization': 'Integral_h f(h|E,theta) dh = 1', 'particle': 'total_nue', 'flavour_name': 'nue', 'alpha_deg': 41.25, 'theta_deg': 43.5, 'angle_units': 'deg', 'angle_convention': {'alpha_deg': 'detector angle, when provided by the caller', 'theta_deg': 'surface-intersection atmospheric angle'}, 'tensor_shapes': {'theta_deg': (), 'E_grid_GeV': (5,), 'X_grid_gcm2': (10,), 'h_grid_km': (20,), 'flux_XE': (10, 5), 'flux_smooth_XE': (10, 5), 'dPhi_dX_XE': (10, 5), 'X_of_h_gcm2': (20,), 'dXdh_gcm2_per_km': (20,), 'source_Eh': (5, 20), 'f_Eh': (5, 20), 'phi_E_obs': (5,), 'phi_Eh': (5, 20), 'alpha_deg': ()}, 'format': 'torch', 'extension': '.pt'}
------------------------------------------------------------------------------------------
PASSED: test_load_phi_Eh_alpha_theta_from_config


## Test: `test_loaded_values_match_saved_values`

**What is checked:** Loaded values match saved values behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: 0.0.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [23]:
run_notebook_test(TEST_MODULE.test_loaded_values_match_saved_values)


Running test_loaded_values_match_saved_values ...
max difference phi_Eh: 0.0
------------------------------------------------------------------------------------------
PASSED: test_loaded_values_match_saved_values


## Test: `test_loaded_dtype_can_be_cast`

**What is checked:** Loaded dtype can be cast behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [24]:
run_notebook_test(TEST_MODULE.test_loaded_dtype_can_be_cast)


Running test_loaded_dtype_can_be_cast ...
loaded dtype: torch.float32
------------------------------------------------------------------------------------------
PASSED: test_loaded_dtype_can_be_cast


## Test: `test_load_missing_file_raises`

**What is checked:** Load missing file raises behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_raises.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_load_missing_file_raises`

This block generates or validates files in `OUTPUT_DIR`:

- `missing_file_that_does_not_exist.pt`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [25]:
run_notebook_test(TEST_MODULE.test_load_missing_file_raises)


Running test_load_missing_file_raises ...
------------------------------------------------------------------------------------------
PASSED: test_load_missing_file_raises


## Test: `test_overwrite_false_returns_existing_file`

**What is checked:** Overwrite false returns existing file behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [26]:
run_notebook_test(TEST_MODULE.test_overwrite_false_returns_existing_file)


Running test_overwrite_false_returns_existing_file ...
path1: V:\output\test\mceq\test5_io\phi_E_theta_h_from_mceq_profiles_numu_theta_30p000deg.pt
path2: V:\output\test\mceq\test5_io\phi_E_theta_h_from_mceq_profiles_numu_theta_30p000deg.pt
------------------------------------------------------------------------------------------
PASSED: test_overwrite_false_returns_existing_file


## Test: `test_list_torch_files`

**What is checked:** List torch files behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [27]:
run_notebook_test(TEST_MODULE.test_list_torch_files)


Running test_list_torch_files ...
files: ['V:\\output\\test\\mceq\\test5_io\\phi_E_theta_h_from_mceq_profiles_numu_theta_0p000deg.pt', 'V:\\output\\test\\mceq\\test5_io\\phi_E_theta_h_from_mceq_profiles_numu_theta_45p000deg.pt']
------------------------------------------------------------------------------------------
PASSED: test_list_torch_files


## Test: `test_load_directory`

**What is checked:** Load directory behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; 0.0; 45.0.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [28]:
run_notebook_test(TEST_MODULE.test_load_directory)


Running test_load_directory ...
loaded groups: dict_keys(['total_nue', 'numu'])
numu phi shape: torch.Size([2, 5, 20])
------------------------------------------------------------------------------------------
PASSED: test_load_directory


## Test: `test_load_directory_can_group_by_flavour_name`

**What is checked:** Load directory can group by flavour name behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [29]:
run_notebook_test(TEST_MODULE.test_load_directory_can_group_by_flavour_name)


Running test_load_directory_can_group_by_flavour_name ...
loaded groups: dict_keys(['numu'])
------------------------------------------------------------------------------------------
PASSED: test_load_directory_can_group_by_flavour_name


## Test: `test_load_directory_keeps_alpha_grid_when_available`

**What is checked:** Load directory keeps alpha grid when available behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; 10.0; 20.0.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_load_directory_keeps_alpha_grid_when_available`

This block generates or validates files in `OUTPUT_DIR`:

- `flux.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [30]:
run_notebook_test(TEST_MODULE.test_load_directory_keeps_alpha_grid_when_available)


Running test_load_directory_keeps_alpha_grid_when_available ...
alpha grid: tensor([10., 20.], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_load_directory_keeps_alpha_grid_when_available


## Test: `test_load_directory_sorts_by_alpha_when_available`

**What is checked:** Load directory sorts by alpha when available behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_close.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check; missing or blank plots may indicate a path, backend, or non-finite numerical-data problem.


### Output files for `test_load_directory_sorts_by_alpha_when_available`

This block generates or validates files in `OUTPUT_DIR`:

- `flux.npz`

The expected result is that each relevant image or data artifact is written to disk and, for figures, also displayed inline when `SHOW_PLOTS = True`. Possible problems include a non-writable output directory, an inactive Matplotlib backend, missing optional external data, or upstream numerical values that make the plotted curves empty or non-finite.


In [31]:
run_notebook_test(TEST_MODULE.test_load_directory_sorts_by_alpha_when_available)


Running test_load_directory_sorts_by_alpha_when_available ...
sorted alpha grid: tensor([10., 20., 30.], dtype=torch.float64)
aligned phi values: tensor([10., 20., 30.], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_load_directory_sorts_by_alpha_when_available


## Test: `test_list_missing_directory_raises`

**What is checked:** List missing directory raises behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_raises.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; optional MCEq/crflux dependencies or atmospheric-model availability can affect this check.


In [32]:
run_notebook_test(TEST_MODULE.test_list_missing_directory_raises)


Running test_list_missing_directory_raises ...
------------------------------------------------------------------------------------------
PASSED: test_list_missing_directory_raises
